name: Create code base visualization
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1

